[package]
name = "netlib"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
zerocopy = { version = "0.8.39", features = ["derive"] }
bytes = "1.11.1"